carts/urls.py
from django.urls import re_path,path
from . views import cart_home,cart_update,checkout_home,checkout_done
app_name='carts'

urlpatterns=[
    re_path(r'^$',cart_home,name='cart_home'),
    re_path(r'^update/$',cart_update,name='update'),
    re_path(r'^checkout/$',checkout_home,name='checkout'),
    re_path(r'^checkout/success/$',checkout_done,name='success'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,re_path,include
from product import  views
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,LogoutView
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from accounts.views import guest_login_form
from accounts.views import LoginView as login_view
from . import views as ecommerceview
from carts.views import cart_detail_api_view
from search.views import getProducts

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$',ecommerceview.HomeView.as_view(),name='home'),
    re_path('^contact/$',ecommerceview.ContactView,name='contact'),
    re_path(r'^login/$',login_view,name='login'),
    re_path(r'^logout/$',LogoutView.as_view(),name='logout'),
    path('accounts/',include('accounts.urls')),
    path('orders/',include('orders.urls')),
    path('product/',include('product.urls')),
    re_path(r'^search/$',include('search.urls')),
    re_path(r'^api/cart/$',cart_detail_api_view,name='api_cart'),
    path('carts/',include('carts.urls')),
    re_path(r'^checkout/address/create/$',checkout_address_create_view,name='checkout_address_create'),
    re_path(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='checkout_address_reuse'),
    re_path(r'^register/guest$',guest_login_form,name='guest_register'),
    re_path(r'^get_products/',getProducts,name='get_products'),
    re_path(r'^theme/$',ecommerceview.dark_mode,name='dark_mode'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path,re_path
from . import views


app_name='product'

urlpatterns=[
    #path('<slug:slug>',views.display_info),
    re_path('^products/$',views.ProductList.as_view(),name='products'),
    path('product/<slug:slug>',views.ProductDetail.as_view(),name='product_detail')
]

carts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from product.models import Product
from decimal import Decimal
from django.db.models.signals import pre_save,post_save,m2m_changed

# Create your models here.
User=get_user_model()

class CartManager(models.Manager):
    def new_or_get(self,request):
        cart_id=request.session.get('cart_id',None)
        qs=self.get_queryset().filter(id=cart_id)
        if qs.count() ==1:
            new_object=False
            cart_obj=qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user=request.user
                cart_obj.save()
        else:
            cart_obj=self.new(user=request.user)
            new_object=True
            request.session['cart_id']=cart_obj.id
        return cart_obj,new_object
    
    def new(self,user=None):
        user_obj=None
        if user is not None:
            if user.is_authenticated:
                user_obj=user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user=models.ForeignKey(User,null=True,blank=True,on_delete=models.CASCADE)
    products=models.ManyToManyField(Product,blank=True)
    subtotal=models.DecimalField(max_digits=100,default=0.00, decimal_places=2)
    total=models.DecimalField(max_digits=100,default=0.00, decimal_places=2)
    updated=models.DateTimeField(auto_now=True)
    timestamp=models.DateTimeField(auto_now_add=True)
    
    objects=CartManager()
    
    def __str__(self):
        return str(self.id)
    

def m2m_changed_cart_reciever(sender,instance,action,*args,**kwargs):
    if action== 'post_add' or 'post_remove' or 'post_clear':
        products=instance.products.all()
        total=0
        for x in products:
            total+=x.price
        if instance.subtotal !=total:
            instance.subtotal=total
            instance.save()
m2m_changed.connect(m2m_changed_cart_reciever,sender=Cart.products.through)
        
def pre_save_cart_reciever(sender,instance,*args,**kwargs):
    if instance.subtotal >0:
        instance.total=instance.subtotal*Decimal(1.08 )
    else:
        instance.total=0.00

pre_save.connect(pre_save_cart_reciever,sender=Cart)
    

carts/views.py
from django.shortcuts import render, redirect
from product.models import Product
from . models import Cart
from orders.models import Order
from accounts.models import GuestEmail
from billing.models import BillingProfile
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from addresses.models import Address

from accounts.forms import GuestForm

from addresses.forms import AddressForm

from django.http import JsonResponse

import razorpay
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    product=[{'id':x.id,'title':x.title, 'price':x.price,'url':x.get_absolute_url()} for x in cart_obj.products.all()]
    cart_data={'product':product,'subtotal':cart_obj.subtotal, 'total':cart_obj.total}
    if is_ajax(request):
        return JsonResponse(cart_data)
    return redirect('carts:cart_home')


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, 'carts/home.html', {'cart': cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
            
    if product_id is not None:
        try:
            product_obj = Product.objects.get(
                id=request.POST.get('product_id'))
        except Product.DoesNotExist:
            print("Show User Product is gone?")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added=False
        else:
            cart_obj.products.add(product_obj)
            added=True
    request.session['cart_items'] = cart_obj.products.count()
    if is_ajax(request):
        print("Ajax request")
        json_data={
            'added':added,
            'removed':not added,
            'count':cart_obj.products.count()
        }
        return JsonResponse(json_data)
    return redirect('carts:cart_home')
    # return redirect(product_obj.get_absolute_url())

@csrf_exempt
def checkout_home(request):
    context={}
    print(request.session.get('guest_email_id'))
    cart_obj, cart_created = cart_obj, new_obj = Cart.objects.new_or_get(
        request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect('carts:cart_home')
    
    Guestform = GuestForm()
    form = AuthenticationForm()
    address_form=AddressForm()
    billing_address_form=AddressForm()
    
    billing_address_id=request.session.get('billing_address_id', None)
    shipping_address_id=request.session.get('shipping_address_id', None)
    
    if request.method == "POST" and not request.user.is_authenticated and not request.session.get('guest_email_id'):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"], password=form.cleaned_data["password"])
            if user is not None:
                login(request, user)
                try:
                    del request.session['guest_email_id']
                    guest_email_id = None
                except:
                    pass
            else:
                return JsonResponse({'errors':form.errors.as_json(),'type':'error'},safe=False)
        else:
            return JsonResponse({'errors':form.errors.as_json(),'type':'error'},safe=False)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs=None
    
    if billing_profile is not None:
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)        
        context.update({
            'totalforpayment':order_obj.order_total*100,
        })
        if request.user.is_authenticated:
            address_qs=Address.objects.filter(billing_profile=billing_profile)    
        if shipping_address_id:
            order_obj.shipping_address_id = Address.objects.get(id=shipping_address_id)
        
        if billing_address_id:
            order_obj.billing_address_id = Address.objects.get(id=billing_address_id)
        
        if billing_address_id or shipping_address_id:
            order_obj.save()

    next = request.build_absolute_uri
    
    
    #razorpay connection
    client = razorpay.Client(auth=("rzp_test_ToOn74RDxVzoCc", "92zqvK5I7UCSeXbIqF9aQrCf"))

    DATA = {
        "amount": 100,
        "currency": "INR",
        "receipt": "receipt#1",
        'payment_capture':1,
        "notes": {
            "key1": "value3",
            "key2": "value2"
        }
    }
    {  "razorpay_payment_id": "pay_29QQoUBi66xm2f",  "razorpay_order_id": "order_9A33XWu170gUtm",  "razorpay_signature": "9ef4dffbfd84f1318f6739a3ce19f9d85851857ae648f114332d8401e0949a3d"}
    payment=client.order.create(data=DATA)
    
    if request.method=="POST":
        is_done=order_obj.check_done(request)
        if is_done:
            order_obj.mark_paid(request)
            request.session['cart_items']=0
            del request.session['cart_id']
            return redirect('carts:success') 
        
    context.update({
        'object': order_obj,
        'billing_profile': billing_profile,
        'form': form,
        'next': next,
        'guestform': Guestform,
        'address_form':address_form,
        'billing_address_form':billing_address_form,
        'address_qs':address_qs,
    })

    return render(request, 'carts/checkout.html', context)


def checkout_done(request):
    
    return render(request,'carts/checkout_done.html')

carts/templates/carts/checkout.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{% load static %}

{% if not billing_profile %}
        <div class="container m-5">
        <div class="row logindivcheckout">
            <p class="lead">Login</p>

            <form action={% url 'carts:checkout' %} method="post" class='loginformdivcheckout' id='user_login_form_checkout'>
                {% if next %}
                <input type="hidden" name="next_url" value="{{next}}"> 
                {% csrf_token %}
            {%bootstrap_form login_form%}
            <input type="submit" value="Login" class="btn btn-primary mt-3">
            {% endif %}
        </form>

        <script>
            $(document).ready(function() {
                var form=$('#user_login_form_checkout')
                form.submit(function(event){
                    event.preventDefault();
                    var thisForm = $(this)
                    var actionEndPoint=thisForm.attr('action')
                    var httpMethod=thisForm.attr('method')
                    var formData=thisForm.serialize();
                    $.ajax({
                      url: actionEndPoint,
                      method: httpMethod,
                      data:formData,  
                      success: function(response){
                        if(response.type=='error'){
                            
                          console.log(response.errors)
                         $('.loginformdivcheckout').hide()
                          $('.logindivcheckout').prepend(`<div class="alert alert-danger erroralert" role="alert">
                              <li>${response.errors}</li>
                                  <div class='container text-center'><button id='fillagain' class='btn btn-warning'>Fill Again</button></div>
                            </div>`)
                            $('#fillagain').click(function(){
                              $('.loginformdivcheckout').show()
                            $('.erroralert').remove();
                          })
                      }
                      else{
                        window.location.reload()
                      }
                      },
                      error:function(errorData){
                        console.log(errorData)
                      }
                    })
                })
            })
        </script>
        </div>

        <div class="row">
            <p class="lead">Continue as guest</p>
            <form action={% url 'guest_register' %} method="post">
                {% if next %}
                <input type="hidden" name="next_url" value="{{next}}"> 
                {% csrf_token %}
            {%bootstrap_form guestform%}
            <input type="submit" value="Register" class="btn btn-primary mt-3">
            {% endif %}
        </form>
        </div>

        </div>
{% else %}
        {% if not object.shipping_address%}
        <h3 class="text-center">Shipping Address Form</h3>
        <hr>
        <div class="row">
            {% include 'addresses/form.html' with address_type='shipping'%}
            </div>
            <div class="row">
            {% include 'addresses/previous_addresses.html' with address_qs=address_qs next_url=next address_type='shipping'%}
            </div>
        </div>
        {% elif not object.billing_address %}
        <h3 class="text-center">Billing Address Form</h3>
        <hr>
        <div class="row">
            {% include 'addresses/previous_addresses.html' with address_qs=address_qs next_url=next address_type='billing'%}
        </div>
        <div class="row">
            {% include 'addresses/form.html' with address_type='billing'%}
        </div>
        </div>
        {% else %}
        <div class="container text-center shadow-lg pb-3">


            <h1>Finalize Checkout</h1>
            <p>Cart Items: {% for product in object.cart.products.all %}{{product}}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
            <p>Cart Total: {{object.cart.total}}</p>
            <p>Shipping Address: {{object.shipping_address_id.address}}</p>
            <p>billing Address: {{object.billing_address_id.address}}</p>
            <p>Shipping total: {{object.shipping_total}}</p>
            <p>Order Total: {{object.order_total}}</p>
            <form action="{% url 'carts:checkout' %}" method="POST">
                {% csrf_token %}
                <script
                    src="{% static 'simplesocial/js/checkout.js' %}"
                    data-key="rzp_test_ToOn74RDxVzoCc" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                    data-amount="{{totalforpayment}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
                    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
                    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
                    data-buttontext="Checkout"
                    data-name="Finalize Chekout"
                    data-description="Cart Total: {{object.cart.total}} Shipping Total: {{object.shipping_total}}"
                    data-prefill.name="{{request.user.username}}"
                    data-prefill.email="{{request.user.email}}"
                    data-theme.color="#F37254"
                ></script>
                <input type="hidden" custom="Hidden Element" name="hidden">
                </form>
        </div>

            </div>
    {% endif %}
{% endif %}

{% endblock content %}

carts/templates/carts/checkout_done.html
{% extends 'base.html' %}
 
{% block content %}

<div class="container text-center mt-5">
    <h1>
        Thank You For Ordering!
    </h1>
</div>
{% endblock content %}

carts/templates/carts/home.html
{% extends 'base.html' %}
{% block content %}
<style>
  .table{
    background-color: black;
    color:white;
  }
</style>
<div class="container text-center table bg-gradient shadow-lg p-2">
<h1>Cart</h1>
{% if cart.products.exists %}
<table class="table cart_table bg-gradient" id='table'>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product Name</th>
        <th scope="col">Product Price</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody class='cart_body' >
      <div>
    {% for product in cart.products.all %}
      <tr class="cart_products">
        <th scope="row">{{forloop.counter}}</th>
        <td><b><a href='{{product.get_absolute_url}}' class='link-primary'>{{product.title}}</a></b></td>
        <td>{{product.price}}</td>
        <td>{% include 'carts/snippets/remove_from_cart.html' with product_id=product.id %}</td>
      </tr>
      {% endfor %}
    </div>
       <tr>
        <td colspan="3"></td>
        <td><span class="cart_subtotal"><b>Subtotal: </b>{{cart.subtotal}}</span></td>
      </tr>
      <tr>
        <td colspan="3"></td>
        <td><span class="total"><b>Total: </b>{{cart.total|floatformat:2}}</span></td>
      </tr>
      <tr>
        <td colspan="4"><a href={% url 'carts:checkout' %} class="btn col-12 btn-outline-success">Checkout</a></td>
      </tr>
    </tbody>
  </table>
  <a href="{% url 'product:products' %}" class="btn btn-outline-primary mt-5 c-12 btn-lg">Add More Products To Cart</a>
  {% else %}
  <span class="lead">Cart Is Empty</span><br>
  <a href="{% url 'product:products' %}" class="btn btn-outline-primary mt-5 mb-3 c-12 btn-lg">Add Products To Cart</a>
  {% endif %}
</div>

<div class="cart_remove_button_form" style="display: none;">
  {% include 'carts/snippets/remove_from_cart.html'%}
</div>

<script>
  $(document).ready(function() {
    var remove_product_form=$('.remove_product_form_ajax');
    remove_product_form.submit(function(event){
        event.preventDefault();
        var thisForm=$(this)
        var actionEndPoint="{% url 'carts:update' %}"
        var httpmethod=thisForm.attr('method')
        var formData=thisForm.serialize()
        $.ajax({
          url: actionEndPoint,
          method: httpmethod,
          data:formData,
          success:function(data){
            console.log('Success!',data);
            var NavbarCartItemCount=$('#cart_item_count')
            NavbarCartItemCount.text(data.count) 
            var currentPath=window.location.href
            if (currentPath.indexOf('/carts/') != -1){
              refreshCart()
            }               
          },
          error:function(errorData){
            console.log(errorData)
        }
        });
    });
    function refreshCart(){
      console.log('in current cart')
      var cartTable=$('.cart_table')
      var cartBody=cartTable.find('.cart_body')
      var cartProducts=cartTable.find('.cart_products')
      var cartSubTotal=cartTable.find('.cart_subtotal')
      var cartTotal=cartTable.find('.total')
      var refreshCartUrl= '/api/cart/'
      var refreshCartMethod="GET";
      var data={};
      $.ajax({
        url:refreshCartUrl,
        method:refreshCartMethod,
        data:data,
        success:function(data){
          $("body").load(`{% url 'carts:cart_home' %}`);
          
        //  var cartForm=$('.cart_form')
//
        //  if(data.product.length>0){
        //    var i=0
        //    cartProducts.empty();
        //    console.log(data.product)
        //    var cartRemove=$('.cart_remove_button_form')
        //    
        //    for(var item in data.product){
//
        //      var newcartitemremove=cartRemove.clone();
        //      newcartitemremove.find('.remove_form_id').val(data.product[item].id)
        //      cartBody.prepend("<tr><th scope=row>"+i+"</th><td><b><a href="+data.product[item].url+"class=link-primary>"+data.product[item].title+"</a></b></td><td>"+data.product[item].price+"</td><td>"+newcartitemremove.html()+"</td></tr>");
        //      i++;
        //    }
        //    cartSubTotal.html('<b>Total: </b>'+data.subtotal);
        //    cartTotal.html('<b>Total: </b>'+data.total);
        //  }
        //  else{
        //    window.location.reload();
        //  }

        },
        error:function(errorData){
          console.log('error',errorData) 
        }
      })
      }
  });
</script>

{% endblock content %}