carts/urls.py
from django.urls import re_path,path
from . views import cart_home,cart_update,checkout_home,checkout_done
app_name='carts'

urlpatterns=[
    re_path(r'^$',cart_home,name='cart_home'),
    re_path(r'^update/$',cart_update,name='update'),
    re_path(r'^checkout/$',checkout_home,name='checkout'),
    re_path(r'^checkout/success/$',checkout_done,name='success'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,re_path,include
from product import  views
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,LogoutView
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from accounts.views import guest_login_form
from accounts.views import LoginView as login_view
from . import views as ecommerceview
from carts.views import cart_detail_api_view
from search.views import getProducts

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$',ecommerceview.HomeView.as_view(),name='home'),
    re_path('^contact/$',ecommerceview.ContactView,name='contact'),
    re_path(r'^login/$',login_view,name='login'),
    re_path(r'^logout/$',LogoutView.as_view(),name='logout'),
    path('accounts/',include('accounts.urls')),
    path('orders/',include('orders.urls')),
    path('product/',include('product.urls')),
    re_path(r'^search/$',include('search.urls')),
    re_path(r'^api/cart/$',cart_detail_api_view,name='api_cart'),
    path('carts/',include('carts.urls')),
    re_path(r'^checkout/address/create/$',checkout_address_create_view,name='checkout_address_create'),
    re_path(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='checkout_address_reuse'),
    re_path(r'^register/guest$',guest_login_form,name='guest_register'),
    re_path(r'^get_products/',getProducts,name='get_products'),
    re_path(r'^theme/$',ecommerceview.dark_mode,name='dark_mode'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path,re_path
from . import views


app_name='product'

urlpatterns=[
    #path('<slug:slug>',views.display_info),
    re_path('^products/$',views.ProductList.as_view(),name='products'),
    path('product/<slug:slug>',views.ProductDetail.as_view(),name='product_detail')
]

search/urls.py
from django.urls import re_path,path
from search.views import SearchProduct

app_name='search'

urlpatterns=[
    re_path(r'^$',SearchProduct.as_view(),name='query')
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from operator import is_
from django.shortcuts import render

from django.views.generic import ListView
from product.models import Product
from carts.views import is_ajax
from tags.models import Tag
from django.http import JsonResponse

# Create your views here.

def getProducts(request):
    tag_list = Tag.objects.all().values()
    product_list=Product.objects.all().values()
    return JsonResponse({'products':list(product_list),'tag':list(tag_list)})

class SearchProduct(ListView):
    template_name='search/view.html'
    context_object_name='products'
    def get_queryset(self):
        
        method_dict=self.request.GET
        query=method_dict.get('q',None)
        if query is not None:
            queryset=Product.objects.search(query)
            return queryset
        return Product.objects.featured()
        

search/templates/search/view.html
{% extends 'base.html' %}
{% block content %}

<div class="row text-center">
    {% if request.GET.q %}
    <div class="col-12">
        <h2>You have searched for <b>{{request.GET.q}}
        </b></h2>
    </div>
    {% endif %}
</div>

<div class="row mt-5 g">
    {% for i  in products %}
    <div class="col-sm-6 col-xs-12 col-lg-4 col-md-4 col-xl-3">
        <div class="card shadow-lg p-2 m-2 border border-light" style="width:35vh;" id="other-components">
          <div style="height:30vh;">
            <img src="{{i.image}}" class="card-img-top" alt="..." width="100%" height="100%">
          </div>
            <div class="card-body">
              <h5 class="card-title">Title: {{i.title |lower}}</h5>
              <p>Price: {{i.price}} Rs.</p>
              <a href={% url 'product:product_detail' slug=i.slug %} class="btn btn-primary">Details</a>
            </div>
          </div>
    </div>
    {% endfor %}
</div>
{% endblock  %}