accounts/urls.py
from django.urls import path,re_path
from . import views

app_name='accounts'

urlpatterns=[
    re_path(r'^$',views.SignupProcess.SignUpView,name='signup'),    
    path('active/<str:encoded>',views.SignupProcess.active_account,name='active'),
    re_path(r'^Activated/$',views.SignupProcess.activated,name='activated'),
    re_path(r'^Expired/$',views.SignupProcess.the_link_has_been_expired,name='expired'),
    re_path(r'^username_for_reset_password/$',views.username_for_reset_password,name='username_for_reset_password'),
    path('reset_password_page/<str:username>/<str:token>',views.reset_password_page,name='reset_password_page'),
    re_path(r'^reset_password/$',views.reset_password,name='reset_password'),
    re_path(r'^change_password/$',views.change_password,name='change_password'),
    
]

carts/urls.py
from django.urls import re_path,path
from . views import cart_home,cart_update,checkout_home,checkout_done
app_name='carts'

urlpatterns=[
    re_path(r'^$',cart_home,name='cart_home'),
    re_path(r'^update/$',cart_update,name='update'),
    re_path(r'^checkout/$',checkout_home,name='checkout'),
    re_path(r'^checkout/success/$',checkout_done,name='success'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,re_path,include
from product import  views
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,LogoutView
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from accounts.views import guest_login_form
from accounts.views import LoginView as login_view
from . import views as ecommerceview
from carts.views import cart_detail_api_view
from search.views import getProducts

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$',ecommerceview.HomeView.as_view(),name='home'),
    re_path('^contact/$',ecommerceview.ContactView,name='contact'),
    re_path(r'^login/$',login_view,name='login'),
    re_path(r'^logout/$',LogoutView.as_view(),name='logout'),
    path('accounts/',include('accounts.urls')),
    path('orders/',include('orders.urls')),
    path('product/',include('product.urls')),
    re_path(r'^search/$',include('search.urls')),
    re_path(r'^api/cart/$',cart_detail_api_view,name='api_cart'),
    path('carts/',include('carts.urls')),
    re_path(r'^checkout/address/create/$',checkout_address_create_view,name='checkout_address_create'),
    re_path(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='checkout_address_reuse'),
    re_path(r'^register/guest$',guest_login_form,name='guest_register'),
    re_path(r'^get_products/',getProducts,name='get_products'),
    re_path(r'^theme/$',ecommerceview.dark_mode,name='dark_mode'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

class GuestEmail(models.Model):
    email=models.EmailField()
    active=models.BooleanField(default=True)
    update=models.DateTimeField(auto_now=True)
    timestamp=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email

accounts/forms.py
from webbrowser import get
from django import forms
from django.contrib.auth.forms import  UserCreationForm
from . import models
from django.contrib.auth import get_user_model

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget=forms.TextInput(attrs={
            'pattern':'[A-Za-z0-9@_+-.]+',
            'id':'signupusername',
        })
        self.fields['password1'].widget=forms.PasswordInput(attrs={
            'id':'signuppassword',
            'minlength':'8'
        })
        self.fields['password1'].widget=forms.PasswordInput(attrs={
            'id':'signupconfirmpassword',
            'minlength':'8'
        })

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

class SignUpForm(UserCreateForm):
    class Meta:
        model=get_user_model()
        fields=('username','email','password1','password2')

    
class GuestForm(forms.ModelForm):
    class Meta:
        model=models.GuestEmail
        fields=('email',)
    
    
class UsernameForPasswordReset(forms.Form):
    username=forms.CharField(max_length=255)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget=forms.TextInput(attrs={
            'pattern':'[A-Za-z0-9@_+-.]+',
            'id':'signupusername',
        })
    
    
    

accounts/views.py
from email.mime import base
from django.shortcuts import render,redirect
from django.urls import reverse,reverse_lazy
from . import forms
from django.utils.http import url_has_allowed_host_and_scheme
from . import models
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm
from django.http import HttpResponseRedirect,JsonResponse,HttpResponse
from django.contrib.auth import login,authenticate
from django.utils.html import strip_tags    
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from uuid import uuid4
import datetime
import json
import time
import jwt

# Create your views here.

def LoginView(request):
    form = AuthenticationForm(request=request, data=request.POST)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            print(user)
            login(request, user)
            print('logged in')
            return HttpResponseRedirect(reverse('home'))
        else:
            return JsonResponse({'errors':form.errors.as_json(),'type':'error'},safe=False)
    else:
        return JsonResponse({'errors':form.errors.as_json(),'type':'error'},safe=False)
    return HttpResponseRedirect(reverse('home'))
    
class SignupProcess():
    def SignUpView(request):
        SignupProcess.form=forms.SignUpForm(request.POST or None)    
        if SignupProcess.form.is_valid():
            try:                
                current_time=time.time()
                usernames=request.POST.get('username')
                message=jwt.encode({
                    'username':usernames,
                    'time':current_time,
                    'form_data':SignupProcess.form.cleaned_data
                },'djangoecommerce',algorithm="HS256")
                
                subject='Account Activation From eCommerce Website'
                html_message = render_to_string('account_activation.html',{'domain':request.get_host(),'encoded':message})
                plain_message = strip_tags(html_message)
                email_from ='manavshah1011.ms@gmail.com'
                send_mail(subject, plain_message, email_from, [request.POST.get('email'),], html_message=html_message,fail_silently=False)
                return JsonResponse({'url':'accounts:check','type':'success'})
            except Exception as e:
                print(e)
                error=str(e)
                print('Exception Occured')
                return JsonResponse({'Exception':'occured','content':error})
        else:
            return JsonResponse({'errors':SignupProcess.form.errors.as_json(),'type':'error'},safe=False)

        
    def active_account(request,encoded):
        decoded=jwt.decode(encoded,'djangoecommerce',algorithms="HS256")
        username=decoded['username']
        email=decoded['form_data']['email']
        password=decoded['form_data']['password1']
        responsetime=time.time()
        try:
            User.objects.get(username=username)
            print('user exists')
            return HttpResponseRedirect(reverse('accounts:expired'))
        except Exception as e:
            print(e)
            timedelta=responsetime-decoded['time']
            print(timedelta/60)
            if timedelta/60 < 5:
                user=User(username=username)
                user.email=email
                user.set_password(password)
                user.save()
                return HttpResponseRedirect(reverse('accounts:activated'))
            else:        
                print('time over')
                return HttpResponseRedirect(reverse('accounts:expired'))            
          
      
        

    def activated(request):
        return render(request,'activated.html')

    def the_link_has_been_expired(request):
        return render(request, 'link_has_been_expired.html')



def username_for_reset_password(request):
    try:
        print(request.POST)
        username_for_reset_password.rand_token = uuid4()
        print(username_for_reset_password.rand_token)
        str_token=str(username_for_reset_password.rand_token)
        user_obj=User.objects.get(username=request.POST.get('username'))
        subject='Password Reset Link'
        html_message = render_to_string('reset_password_link.html',{'domain':request.get_host(),'username':request.POST.get('username'),'token':str_token})
        plain_message = strip_tags(html_message)
        email_from ='manavshah1011.ms@gmail.com'
        recipirent_list=[user_obj.email,]
        print(send_mail(subject, plain_message, email_from, recipirent_list, html_message=html_message,fail_silently=False)) 
        username_for_reset_password.current_time=datetime.datetime.now()
        print(username_for_reset_password.current_time)
        return JsonResponse({'type':'success'})
    except Exception as e:
        error=str(e)
        print('Exception Occured')
        return JsonResponse({'Exception':'occured','content':error})
    
def reset_password_page(request,username,token):
    context={
        'username':username,
        'token':token
    }
    return render(request, 'reset_password.html',context)



def reset_password(request):
    if request.method == 'POST':
        formreceivedtime=datetime.datetime.now()
        print(formreceivedtime)
        onetimetoken=request.POST.get('onetimetoken')
        try:
            delta=formreceivedtime-username_for_reset_password.current_time
            print(delta.total_seconds()/60)
            print(username_for_reset_password.rand_token)
            if onetimetoken == str(username_for_reset_password.rand_token) and delta.total_seconds()/60 <=5:
                username=request.POST.get('username')
                password=request.POST.get('password')
                print(password)
                user_obj=User.objects.get(username=username)
                user_obj.set_password(password)
                user_obj.save()
                username_for_reset_password.rand_token= uuid4()
                print(username_for_reset_password.rand_token)
                return JsonResponse({'content':'Password has been changed','result':'success'})
            else:
                return JsonResponse({'content':'Password Reset link has been expired','result':'error'})
        except:
            print('An exception has occured')
            return JsonResponse({'content':'Password Reset link has been expired' ,'result':'error'})
    
    
def change_password(request):
    if request.method == 'POST':
        form=PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return JsonResponse({'content':'Password has been changed','type':'success'})
        else:
            print('form is not valid')
            return JsonResponse({'errors':form.errors.as_json(),'type':'error'},safe=False)
            
    else:
        form=PasswordChangeForm(request.user)
        
    
def guest_login_form(request):
    form=forms.GuestForm(request.POST or None)
    context={
        'form': form,
    }
    if form.is_valid():
        next=request.GET.get('next_url')
        next_post=next=request.POST.get('next_url')
        redirect_path=next or next_post
        email=form.cleaned_data['email']
        new_guest_email=models.GuestEmail.objects.create(email=email)
        request.session['guest_email_id']=new_guest_email.id
        if url_has_allowed_host_and_scheme(redirect_path,request.get_host()):
            return redirect(redirect_path)
        else:
            return reverse('carts:checkout')
    return reverse('carts:checkout')

            
    
    
    

accounts/templates/link_has_been_expired.html
{% extends 'base.html' %}
{% block content %}
<div class="container text-center mt-5">
    <h1>The link has been expired</h1>
    <h2>You'll Be Redirected To Home Page In: <span id="time">Loading...</span></h2>
</div>
<script>
var time = 5;
setInterval(function() {
  var seconds = time ;
  var minutes = (time - seconds) / 60;
  if (seconds.toString().length == 1) {
    seconds =  seconds;
  }
  document.getElementById("time").innerHTML =+ seconds;
  time--;
  if (time == 0) {
    window.location.href = "{% url 'home' %}";
  }
}, 1000);
</script>

{% endblock content %}

accounts/templates/reset_password.html
{% extends 'base.html' %}
{% block content %}
    <div class="container text-center mt-5 card  border shadow-lg p-3 mb-5 rounded bg-gradient passwordresetdiv" id='other-components'>
        <h4>Heyy {{username}} Here is you reset password form</h4>
        <form action="{% url 'accounts:reset_password' %}" method="post" id='password_reset_form'>
          {% csrf_token %}
          <input type="hidden" name="username" value="{{username}}" />
          <input type="hidden" name="onetimetoken" value="{{token}}" />
            <label for="username" class="form-label"> Enter New Password:</label>
            <input class='form-control' type="password" name="password" id="password1" pattern=".{8,12}" required title="8 to 12 characters">
            <label for="" class="form-label">Confirm New Password:</label>
             <input class='form-control' type="password" id="password2" pattern=".{8,12}" required title="8 to 12 characters">
            <br>
            <input type="submit" value="Change" class='btn btn-outline-success btn-md'>
        </form>
        <script>
          var password = document.getElementById("password1"), confirm_password = document.getElementById("password2");

function validatePassword(){
  if(password.value != confirm_password.value) {
    confirm_password.setCustomValidity("Passwords Don't Match");
  } else {
    confirm_password.setCustomValidity('');
  }
}

password.onchange = validatePassword;
confirm_password.onkeyup = validatePassword;
        </script>
        <script>
          $(document).ready(function(){
            var form=$('#password_reset_form')
            var url=form.attr('action')
            var method=form.attr('method')
            form.submit(function(event){
              var data=form.serialize()
              event.preventDefault();
              $.ajax({
                url:url,
                method:method,
                data:data,
                success:function(response){
                  if(response.result == 'success'){
                    $('.passwordresetdiv').html(`
                    <div class="alert alert-success" role="alert">
                      ${response.content}
                    </div>
                    `)
                  }
                  else{
                    $('.passwordresetdiv').html(`
                    <div class="alert alert-danger" role="alert">
                      ${response.content}
                    </div>
                    `)
                  }
                }
              })
            })
          });
        </script>
    </div>
  {% endblock content %}

accounts/templates/reset_password_link.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div style='text-align: center; border: 3px solid green;'>
        <h1>Heyy {{username}} Here is you reset password  link</h1>
        <h3>This link is one time link and will expire after 5 minutes</h3>
        <p>http://{{domain}}{% url 'accounts:reset_password_page' username=username token=token%}</p>
    </div>
</body>
</html>