accounts/urls.py
from django.urls import path,re_path
from . import views

app_name='accounts'

urlpatterns=[
    re_path(r'^$',views.SignupProcess.SignUpView,name='signup'),    
    path('active/<str:encoded>',views.SignupProcess.active_account,name='active'),
    re_path(r'^Activated/$',views.SignupProcess.activated,name='activated'),
    re_path(r'^Expired/$',views.SignupProcess.the_link_has_been_expired,name='expired'),
    re_path(r'^username_for_reset_password/$',views.username_for_reset_password,name='username_for_reset_password'),
    path('reset_password_page/<str:username>/<str:token>',views.reset_password_page,name='reset_password_page'),
    re_path(r'^reset_password/$',views.reset_password,name='reset_password'),
    re_path(r'^change_password/$',views.change_password,name='change_password'),
    
]

carts/urls.py
from django.urls import re_path,path
from . views import cart_home,cart_update,checkout_home,checkout_done
app_name='carts'

urlpatterns=[
    re_path(r'^$',cart_home,name='cart_home'),
    re_path(r'^update/$',cart_update,name='update'),
    re_path(r'^checkout/$',checkout_home,name='checkout'),
    re_path(r'^checkout/success/$',checkout_done,name='success'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,re_path,include
from product import  views
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,LogoutView
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from accounts.views import guest_login_form
from accounts.views import LoginView as login_view
from . import views as ecommerceview
from carts.views import cart_detail_api_view
from search.views import getProducts

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$',ecommerceview.HomeView.as_view(),name='home'),
    re_path('^contact/$',ecommerceview.ContactView,name='contact'),
    re_path(r'^login/$',login_view,name='login'),
    re_path(r'^logout/$',LogoutView.as_view(),name='logout'),
    path('accounts/',include('accounts.urls')),
    path('orders/',include('orders.urls')),
    path('product/',include('product.urls')),
    re_path(r'^search/$',include('search.urls')),
    re_path(r'^api/cart/$',cart_detail_api_view,name='api_cart'),
    path('carts/',include('carts.urls')),
    re_path(r'^checkout/address/create/$',checkout_address_create_view,name='checkout_address_create'),
    re_path(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='checkout_address_reuse'),
    re_path(r'^register/guest$',guest_login_form,name='guest_register'),
    re_path(r'^get_products/',getProducts,name='get_products'),
    re_path(r'^theme/$',ecommerceview.dark_mode,name='dark_mode'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path,re_path
from . import views
app_name='orders'

urlpatterns=[
    re_path(r'^order_list/$',views.OrderObjects,name='order_list'),
    path('delete_order/<int:pk>',views.DeleteOrder,name='delete_order')
    ]

product/urls.py
from django.urls import path,re_path
from . import views


app_name='product'

urlpatterns=[
    #path('<slug:slug>',views.display_info),
    re_path('^products/$',views.ProductList.as_view(),name='products'),
    path('product/<slug:slug>',views.ProductDetail.as_view(),name='product_detail')
]

templates/account_activation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div style='text-align: center; border: 3px solid green;'>
        <h1>Heyy {{username}} Here is you account activation link</h1>
        <h3>This link is one time link and will expire after 5 minutes</h3>
        <p>http://{{domain}}{% url 'accounts:active' encoded=encoded%}</p>
    </div>
</body>
</html>

templates/account_already_exists.html
{% extends 'base.html' %}
{% block content %}
<div class="container text-center mt-5">
    <h1>Either You Have Typed A Wrong Email Or Your Account Already Exists</h1>
    <h2>Please provide a valid email if already provided check your email for the activation link</h2>
    <h3>You'll Be Redirected To Home Page In: <span id="time">Loading...</span></h3>
</div>
<script>
var time = 5;
setInterval(function() {
  var seconds = time ;
  var minutes = (time - seconds) / 60;
  if (seconds.toString().length == 1) {
    seconds =  seconds;
  }
  document.getElementById("time").innerHTML =+ seconds;
  time--;
  if (time == 0) {
    window.location.href = "{% url 'home' %}";
  }
}, 1000);
</script>

{% endblock content %}

templates/already_active.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container text-center mt-5">
        <h1><h1>You link has been expired</h1><h2>You're account should alreade be active</h2></h1>
        <h2>This page will be closes in: <span id="time">Loading...</span></h2>
    </div>
    <script>
    var time = 5;
    setInterval(function() {
      var seconds = time ;
      var minutes = (time - seconds) / 60;
      if (seconds.toString().length == 1) {
        seconds =  seconds;
      }
      document.getElementById("time").innerHTML =+ seconds;
      time--;
      if (time == 0) {
        window.location.href = "{% url 'home' %}";
      }
    }, 1000);
    </script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <!-- CSS only -->
   {% include 'links.html' %}

{% include 'nav.html'%}
<div class="container  d-flex align-items-center justify-content-center mt-3" style="margin-left:auto;">
<div class="list-group guesseditembox" style='z-index: 99; text-align: center;'></div>
</div>
<style>
  
  #other-components{
    background-color:black;
    color:white;
  }
</style>
</head>

<body id="content" class='text-white'>
        <div class="container">
        {% comment %} {% include 'themes.js.html' %} {% endcomment %}        
    {% block content %}
  {% include 'home.html' %}

{{authentication_form}}
</div>{% endblock content %}
    
</div>


<canvas id="canvas" style="position:fixed; top:0; z-index: -1;" class=''></canvas>
{% include 'master.js.html' %}
</body>
<script src="{% static 'simplesocial/js/csrf.ajax.js' %}"></script>

{% include 'searching_and_cart.html' %}


{% comment %} Modals {% endcomment %}
<div class="modal fade" id="signupmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        {% include 'signup.html' %}
    </div>
  </div>

  <div class="modal fade" id="loginmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
                {% include 'login.html' %}
                
    </div>
  </div>

  <div class="modal fade" id="change_password" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
                {% include 'password_change_form.html' %}
                
    </div>
  </div>

  <div class="modal fade" id="contactmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
                {% include 'contact/contact_page.html' %}
                
    </div>
  </div>

  <div class="modal fade" id="resetpassword" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="container text-center mt-5 card  border shadow-lg p-3 mb-5 rounded bg-gradient modal-content resetpasswordmodal" id='other-components'>
        <form action="{% url 'accounts:username_for_reset_password' %}" method="post" id="submit_username">
          {% csrf_token %}
          {%bootstrap_form usernameforpasswordresetform%}
          <br>
          <div class="" role="status" id='spinner-div'>
        <input type="submit" value="Submit" class="btn btn-primary mt-3 form-control resetbutton">
          </div>
          
          <div id='resetcancel'>
        <input type="button" value="Cancel" class="btn btn-danger mt-3 form-control" data-bs-dismiss="modal" aria-label="Close">
      </div>
      </form> 
      </div>
      
</div>
  </div>

  <script>
    $(document).ready(function() {
      $('#submit_username').submit(function(event){
        $('.resetpassworddiv').hide();
        $('.resetpasswordmodal').prepend(`<div class="alert alert-primary" id='mailsending' role="alert">
          Sending Mail....
        </div>`)
          event.preventDefault()
          var thisForm=$(this)
          var actionuvarrl=thisForm.attr('action')
          var formmethod=thisForm.attr('method')
          var data=thisForm.serialize()
          $.ajax({
            url:actionuvarrl,
            method:formmethod,
            data:data,
            success:function(response){
              if(response.type =='success'){
              $('#spinner-div').removeClass('spinner-border text-primary')
              console.log(response)
              $('.resetpasswordmodal').html(`<div class="alert alert-success" role="alert">
                Password reset link has been sent to you email
              </div>`)
              }
              else if(response.Exception =='occured'){
                $('#mailsending').remove();
                $('.resetpassworddiv').hide()
                $('.resetpasswordmodal').prepend(`<div class="alert alert-danger exceptionalert" role="alert">
                    ${response.content}
                    <div class='container text-center'><button id='fillagain' class='btn btn-warning'>Fill Again</button></div>
                </div>
                `)
                $('#fillagain').click(function(){
                    $('.resetpassworddiv').show()
                    $('.exceptionalert').remove()
                })
            }
            },
            error:function(errorData){
              console.log(errorData)
            }          
          })
      })  




      $('#logout').click(function(event) {
        event.preventDefault()
        $.ajax({
          url: `{% url 'logout' %}`,
          method: 'GET',
          success: function(response){  
            window.history.pushState({page: "another"}, "another page", "{% url 'home' %}");
            window.location.reload();
          },
          error:function(errorData){
            console.log(errorData)
          }
        })
      })
    })
  </script>
  <noscript>
    <div class="container-fluid">
    Please enable javascript to view this page in best condition!!
  </div>
  </noscript>
</html>

templates/check_your_email.html
{% extends 'base.html' %}
{% block content %}
<div class="container text-center mt-5">
    <h1>Activation link has been sent to you email!!</h1>
    <h2>You'll Be Redirected To Home Page In: <span id="time">Loading...</span></h2>
</div>
<script>
var time = 5;
setInterval(function() {
  var seconds = time ;
  var minutes = (time - seconds) / 60;
  if (seconds.toString().length == 1) {
    seconds =  seconds;
  }
  document.getElementById("time").innerHTML =+ seconds;
  time--;
  if (time == 0) {
    window.location.href = "{% url 'home' %}";
  }
}, 1000);
</script>

{% endblock content %}

templates/home.html
<table class="table table-light border border-success border-5">
    <thead>
      <tr>
        <th scope="col" class='text-center'><h3>Core Functionalities</h3></th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
    <tr>
        <td>Fully responsive and runnable on any device</td>
    </tr>
     <tr>
        <td>Both registered and non-registered users can make order</td>
     </tr>
     <tr>
        <td>When user creates an account an activation link is sent to his/her email address. user can activate their account by clicking on the activation link which is a one time link and valid for 5 minutes</td>
     </tr>
     <tr>
        <td>Only users having activated accounts are able to login</td>
     </tr>
     <tr>
        <td>At the time of login django authentication system authenticates the user and only then they are allowed to login</td>
     </tr>
     <tr>
        <td>User can also create guest accounts and use full functionalities of the site</td>
     </tr>
     <tr>
        <td>User can search for the products by their title, tags, descriptions, price.</td>
     </tr>
     <tr>
        <td>Ajax has been used to enable asynchronous functionalities like search predictions, adding or removing product from the cart and many more.</td>
     </tr>
     <tr>
        <td>User can reset his forgotten password and can also change the existing password</td>
     </tr>
     <tr>
        <td>User can create a order and pay easily with any of the available payment options.</td>
     </tr>
    </tbody>
  </table>    
  <table class="table table-light border border-success border-5 mt-5">
    <thead>
      <tr>
        <th scope="col" class='text-center'><h3>Technology Used</h3></th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
     <tr>
        <td>Backend Language - Python</td>
     </tr>
     <tr>
        <td>Framework - Django 4.0.5</td>
     </tr>
     <tr>
        <td>Frontend Language - HTML 5, CSS 3</td>
     </tr>
     <tr>
        <td>Scripting Language - Javascript ES2015</td>
     </tr>
     <tr>
        <td>Additional Libraries - Bootstrap, Jquery</td>
     </tr>
     <tr>
        <td>AJAX for asynchronous communication</td>
     </tr>
     <tr>
        <td>Razorpay payment gateway integration</td>
     </tr>
     <tr>
        <td>codepen.io for particles effect</td>
     </tr>
    </tbody>
  </table>          

templates/links.html
{% load static %}
<link type="image/png" sizes="16x16" rel="icon" href="https://i.ibb.co/DMbj77T/icons8-django-16.png">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.js" integrity="sha512-gY25nC63ddE0LcLPhxUJGFxa2GoIyA5FLym4UJqHDEMHjp8RET6Zn/SHo1sltt3WuVtqfyxECP38/daUc/WVEA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.css" integrity="sha512-UTNP5BXLIptsaj5WdKFrkFov94lDx+eBvbKyoe1YAfjeRPC+gT5kyZ10kOHCfNZqEui1sxmqvodNUx3KbuYI/A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css" integrity="sha512-OTcub78R3msOCtY3Tc6FzeDJ8N9qvQn1Ph49ou13xgA9VsH9+LRxoFU6EqLhW4+PKRfU+/HReXmSZXHEkpYoOA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.green.css" integrity="sha512-riTSV+/RKaiReucjeDW+Id3WlRLVZlTKAJJOHejihLiYHdGaHV7lxWaCfAvUR0ErLYvxTePZpuKZbrTbwpyG9w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.green.min.css" integrity="sha512-C8Movfk6DU/H5PzarG0+Dv9MA9IZzvmQpO/3cIlGIflmtY3vIud07myMu4M/NTPJl8jmZtt/4mC9bAioMZBBdA==" crossorigin="anonymous" referrerpolicy="no-referrer" />



<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}" type="text/css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300&display=swap" rel="stylesheet">

templates/nav.html
{% load bootstrap4 %}
<nav class="navbar navbar-expand-xl navbar-dark shadow-5-strong bg-gradient opacity-100" id="nav">
    <div class="container-fluid">
      <span class="navbar-brand">eCommerce</span>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href={% url 'home' %} id='home_page'>Home</a>
          </li>
          {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" id="signup" href={% url 'accounts:signup' %} data-bs-toggle="modal" data-bs-target="#signupmodal" data-bs-whatever="@mdo">SignUp</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id='login' href={% url 'login' %} data-bs-toggle="modal" data-bs-target="#loginmodal" data-bs-whatever="@mdo">LogIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'product:products' %}" id='products'>Products</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" id='logout' href="{% url 'logout' %}">LogOut</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'product:products' %} id='products'>Products</a>
          </li>
        {% endif %}
        {% if user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link" href={% url 'admin:index' %}>Admin</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'orders:order_list' %}" >Your Orders</a></li>
            <li><a class="dropdown-item" href="#"  data-bs-toggle="modal" data-bs-target="#change_password" data-bs-whatever="@mdo">Change Your Password</a></li>
            {% else %}
            {% if request.session.guest_email_id %}
            <li><a class="dropdown-item" href="{% url 'orders:order_list' %}" >Your Orders</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="#"  data-bs-toggle="modal" data-bs-target="#resetpassword" data-bs-whatever="@mdo">Forgot Password?</a></li>
            {% endif %}
            <li> <a class="dropdown-item" href="{% url 'contact' %}" data-bs-toggle="modal" data-bs-target="#contactmodal" data-bs-whatever="@mdo">Contact</a></li>
            
            {% comment %} <li><hr class="dropdown-divider"></li> {% endcomment %}
            {% comment %} <li><a class="dropdown-item" href="#">Something else here</a></li> {% endcomment %}
          </ul>
        </li>

    </ul>         
      {% include 'search/snippets/search-form.html' %}
  
        <ul class="navbar-nav me-5">
          <li class="nav-item">
            <a class="nav-link position-relative" href={% url 'carts:cart_home' %}>
                <i class="bi bi-cart" style="font-size:2rem;"></i>
                <span class="translate-middle badge text-danger" style="padding:0; position: absolute; top:50;">
                  <span id='cart_item_count'>{{request.session.cart_items}}</span>
                  <span class="visually-hidden">unread messages</span>
                </span>
            </a>
          </li>
        </ul>


            
      </div>
    </div>
  </nav>
  </div>

templates/password_change_form.html
{% load bootstrap4 %}
<div class="container text-center mt-5 card  border shadow-lg p-3 mb-5 rounded bg-gradient modal-content password_change_div" id='other-components'>
  <div class="passwordchangediv">
  <h1>Password Change Form</h1>
    <form action="{% url 'accounts:change_password' %}" method="post" id='passwordchangeform'>
        {% csrf_token %}
        {%bootstrap_form passwordchangeform%}
       <br>
        <input type="submit" value="Change" class="btn btn-primary mt-3 form-control">
        <input type="button" value="Cancel" class="btn btn-danger mt-3 form-control" data-bs-dismiss="modal" aria-label="Close">
    <br>
    </form>
  </div>  
    <script>
        $(document).ready(function() {
            var form=$('#passwordchangeform')
            form.submit(function(event){
                event.preventDefault();
                var thisForm = $(this)
                var actionEndPoint=thisForm.attr('action')
                var httpMethod=thisForm.attr('method')
                var formData=thisForm.serialize();
                $.ajax({
                  url: actionEndPoint,
                  method: httpMethod,
                  data:formData,  
                  success: function(response){
                    if(response.type=='success'){
                      $('.passwordchangediv').hide()
                    $('.password_change_div').prepend(`<div class="alert alert-success" role="alert">
                        Your password has been changed successfully.
                      </div>`)
                    }
                    else if(response.type == 'error'){
                      $('.passwordchangediv').hide()
                      $('.password_change_div').prepend(`
                      <div class="alert alert-danger passwordchangealert" role="alert">
                        ${response.errors}
                        <div class='container text-center'><button id='fillagainpassword' class='btn btn-warning'>Fill Again</button></div>
                      </div>
                      `)
                      $('#fillagainpassword').click(function(){
                          $('.passwordchangealert').remove()
                          form[0].reset()
                          $('.passwordchangediv').show()
                      })
                    }
                  },
                  error:function(errorData){
                    console.log(errorData)
                  }
                })
            })
        })
    </script>
</div>

templates/signup.html
{% load bootstrap4 %}

<div class="container text-center mt-5 card  shadow p-3 mb-5 border shadow-lg p-3 mb-5 rounded bg-gradient modal-content signupdiv" id="other-components">
  <div class="signupformdiv">
    <h1>SignUp Form</h1>
<form action="{% url 'accounts:signup' %}" method="post" id='signupform'>
    {% csrf_token %}
    <span>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
    {%bootstrap_field signup_form.username %}
    {%bootstrap_field signup_form.email %}
    <br>
    <ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul>
    {%bootstrap_field signup_form.password1 %}
    {%bootstrap_field signup_form.password2 %}

    <input type="submit" value="SignUp" class="btn btn-primary mt-3 form-control">
    <input type="btn" value="Cancel" class="btn btn-danger mt-3 form-control" data-bs-dismiss="modal" aria-label="Close">
</form>
</div>
<script>
    $(document).ready(function(){
        var form=$('#signupform')
        var url=form.attr('action');
        method=form.attr('method');
        form.submit(function(event){
            event.preventDefault()
            $('.signupformdiv').hide()
            $('.signupdiv').prepend(`<div class="alert alert-primary sending" role="alert">
                Sending Mail....
              </div>`)
            data=form.serialize()
            $.ajax({
                url:url,
                method:method,
                data:data,
                success:function(response){
                    if(response.type=='success'){
                        $('.sending').remove();
                        $('.signupformdiv').hide()
                        $('.signupdiv').prepend(`
                        <div class="successalert">
                        <div class="alert alert-success" role="alert">
                            <li>Activation link has been sent to you email!!</li>
                        </div>
                        <div class="alert alert-danger" role="alert">
                            <li>If you did not recieve the activation link</li>
                        <li>Then please provide a valid email <div class='container text-center'><button id='signupfillagain' class='btn btn-warning'>Fill Again</button></div></li>
                        </div>
                    </div>
                        `)
                        $('#signupfillagain').click(function(){
                            $('.signupformdiv').show()
                            $('.successalert').remove()
                        })
                    }
                    else if(response.Exception =='occured'){
                        $('.sending').remove();
                        $('.signupformdiv').hide()
                        $('.signupdiv').prepend(`<div class="alert alert-danger signupexceptionalert" role="alert">
                            ${response.content}
                            <span>Check you internet connection</span>
                            <div class='container text-center'><button id='signupfillagain' class='btn btn-warning'>Fill Again</button></div>
                        </div>
                        `)
                        $('#signupfillagain').click(function(){
                            $('.signupformdiv').show()
                            $('.signupexceptionalert').remove()
                        })
                    }
                    else if(response.type=='error'){
                        $('.sending').remove();
                        $('.signupformdiv').hide()
                        console.log(response.errors)
                       
                        $('.signupdiv').prepend(`<div class="alert alert-danger erroralert" role="alert">
                            <li>${response.errors}</li>
                                <div class='container text-center'><button id='signupfillagain' class='btn btn-warning'>Fill Again</button></div>
                          </div>`)
                          $('#signupfillagain').click(function(){
                            
                            $('.signupformdiv').show()
                            $('.erroralert').remove()
                        })
                    }
                }
            });
        })
    });
</script>
</div>